In [1]:
import numpy as np

# Numpy ndarrays and regular lists

In [2]:
a = range(5)
b = [0,1,2,3,4]
print 'a is {} and b is {}'.format(a,b)

a is [0, 1, 2, 3, 4] and b is [0, 1, 2, 3, 4]


In [3]:
c = np.arange(5)
d = np.array([0,1,2,3,4])
print 'c is {} and d is {}'.format(c, d)

c is [0 1 2 3 4] and d is [0 1 2 3 4]


In [4]:
print a+b

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [5]:
print c+d

[0 2 4 6 8]


### What is broadcasting and why does it matter?

let's say that we want b to follow a, we just need to add 5 to each element of b

In [6]:
b = [i+5 for i in b]
print 'this is a slow b', a+b

this is a slow b [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


with numpy it's one operation

In [7]:
d+=5
print 'this is a fast d', np.append(c,d)

this is a fast d [0 1 2 3 4 5 6 7 8 9]


this also works with multiplication and division

In [9]:
c * 20

array([ 0, 20, 40, 60, 80])

In [10]:
d/-2

array([-3, -3, -4, -4, -5])

aaah what happened there? truncation?

#### dtype

In [12]:
a = np.arange(5)
print a.dtype

int64


In [13]:
b = np.arange(5, dtype='float64')
print b.dtype

float64


In [15]:
print (a*b).dtype

float64


available types are:
- bool
- inti
- int8
- int16
- int32
- int64
- uint8
- uint16
- uint32
- uint64
- float16
- float32
- float64 or float

# converting lists to arrays

In [19]:
a = range(5)
b = np.asarray(a)
c = np.array(a)
print "a, b and c are", a, b, c

a, b and c are [0, 1, 2, 3, 4] [0 1 2 3 4] [0 1 2 3 4]


# Multiple dimensions

In [26]:
d = np.array([a,b,c])
e = np.vstack([a,b,c])
f = np.hstack([a,b,c])
print "d is", d
print "e is", e
print "f is", f

d is [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
e is [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
f is [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


`hstack` seen here is roughly equivalent to `np.append` seen before and also `np.concatenate` if you're more into `c` style